version: '3.7'
services:

  tls-status:
    image: tls-status:latest
    build:
        context: .
        dockerfile: Dockerfile
    container_name: tls-status
    restart: always
    dns: 1.1.1.1
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host

