#!/bin/bash

#
# A simple script that obtains the notBefore and the notAfter attributes from
# a X509 certificate of a given domain.
#

SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

set -e

# the first argument of this is the domain
DOMAIN=$1

if [[ -z $DOMAIN ]]; then
	echo "Error: No argument was given."
	exit 1
fi

if [[ ! $DOMAIN =~ ^([0-9a-zA-Z\-]{1,64}\.){1,5}[a-zA-Z]{2,3}$ ]]; then
	echo "Error: the following is an invalid domain... $DOMAIN"
	exit 1
fi

# extract the "notBefore" and "notAfter" attributes from a given certificate
START_END_DATES=$(echo | openssl s_client -showcerts -servername $DOMAIN -connect $DOMAIN:443 2> /dev/null | openssl x509 -noout -dates)

if [[ -z $START_END_DATES ]]; then
	echo "Error: No response was given by server... $DOMAIN"
	exit 1
fi

if [[ ! $START_END_DATES =~ notBefore= ]]; then
	echo "Error: Unable to obtain notBefore attribute from... $DOMAIN"
	exit 1
fi

if [[ ! $START_END_DATES =~ notAfter= ]]; then
	echo "Error: Unable to obtain notAfter attribute from... $DOMAIN"
	exit 1
fi

# print the contents to stdout
echo "$START_END_DATES"
exit 0
